#!/bin/tcsh

# A wrapper to call sips in the correct folder.
# By Richard Koch, May 24, 2012

set tiff_file = "$argv[1]"
set png_file = "$argv[2]"

/usr/bin/sips -s format png "$tiff_file" --out "$png_file"

