#!/bin/tcsh

# This short script calls "synctex edit -o ... " to get synchronization data
# Richard Koch; March 21, 2004

set mytexexecpath = "$argv[1]"
setenv PATH "${mytexexecpath}:${PATH}"
rehash

set argument1 = "$argv[2]"

set argument2 = "$argv[3]"

synctex view -i "${argument1}" -o "${argument2}"
