#!/bin/tcsh

# This short script calls texexec to run a conTeXt job
# Richard Koch; September 14, 2001

set mytexexecpath = "$argv[1]"
if (-x ${mytexexecpath}texexec) then
	setenv PATH "${mytexexecpath}:${PATH}"
	rehash
endif

set pstest = $argv[2]
set filename = "$argv[3]"

texexec "${filename}"

if ("$pstest" == "no") then
	altpdflatex "${filename:r}.dvi"
else
	altpdflatex --keep-psfile "${filename:r}.dvi"
endif

