#!/bin/tcsh

# This short script calls epstopdf in the source code
# Richard Koch; August 5, 2001

if ("$#argv" == "0") then
	echo "$0 Missing argument: eps-file-name"
	exit 1
endif

set filename = "$argv[2]"
set outputname = "${filename:r}.pdf"
set epstopdf = "$argv[1]"

"${epstopdf}" -o="${outputname}" "${filename}"
