#!/bin/tcsh

# A wrapper to call epstopdf in the correct folder.
# By Richard Koch, Oct 4, 2001, following similar code by
# Gerben Wierda

set mygspath = "/usr/local/bin"
if (-x ${mygspath}/gs) then
	setenv PATH "${mygspath}:${PATH}"
	rehash
endif

set filename = "$argv[2]"
set epstopdfname = "$argv[1]"
set outputname = "${filename:r}.pdf"
"${epstopdfname}" -o="${outputname}" "${filename}"

