#!/bin/tcsh

# This short script calls texexec to run a conTeXt job
# Richard Koch; September 14, 2001 and May 29, 2006

set mytexexecpath = "$argv[1]"
if (-x ${mytexexecpath}texexec) then
	setenv PATH "${mytexexecpath}:${PATH}"
	rehash
endif

set filename = "$argv[3]"

if ("$argv[2]" == "YES") then
	texexec --pdf --passon=" --interaction=nonstopmode " "${filename}"
else
	texexec --pdf "${filename}"
endif
