#!/bin/tcsh

# This short script calls texexec to run a conTeXt job
# Richard Koch; September 14, 2001 and May 29, 2006

set mytexexecpath = "$argv[1]"
if (-x ${mytexexecpath}texexec) then
	setenv PATH "${mytexexecpath}:${PATH}"
	rehash
endif

set filename = "$argv[3]"

if (-x /usr/bin/ruby) then

	if (-e /usr/local/teTeX/share/texmf.local/scripts/context/ruby/texmfstart.rb) then
		if ("$argv[2]" == "YES") then
			/usr/bin/ruby /usr/local/teTeX/share/texmf.local/scripts/context/ruby/texmfstart.rb texexec --pdf --passon=" --interaction=nonstopmode " "${filename}"
			exit
		else
			/usr/bin/ruby /usr/local/teTeX/share/texmf.local/scripts/context/ruby/texmfstart.rb texexec --pdf "${filename}"
			exit
		endif
	endif
	
 	if (-e /usr/local/teTeX/share/texmf.tetex/scripts/context/ruby/texmfstart.rb) then
		if ("$argv[2]" == "YES") then
			/usr/bin/ruby /usr/local/teTeX/share/texmf.tetex/scripts/context/ruby/texmfstart.rb texexec --pdf --passon=" --interaction=nonstopmode " "${filename}"
			exit
		else
			/usr/bin/ruby /usr/local/teTeX/share/texmf.tetex/scripts/context/ruby/texmfstart.rb texexec --pdf "${filename}"
			exit
		endif
	endif

else
	
	if ("$argv[2]" == "YES") then
		texexec --pdf --passon=" --interaction=nonstopmode " "${filename}"
	else
		texexec --pdf "${filename}"
	endif
endif
