## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file SageAndLatexmk.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_75 = Integer(75); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_65 = Integer(65); _sage_const_7 = Integer(7); _sage_const_70 = Integer(70); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_80 = Integer(80); _sage_const_82 = Integer(82); _sage_const_0 = Integer(0); _sage_const_90 = Integer(90); _sage_const_31 = Integer(31); _sage_const_30 = Integer(30); _sage_const_32 = Integer(32); _sage_const_86 = Integer(86); _sage_const_6 = Integer(6)## This file (SageAndLatexmk.sagetex.sage) was *autogenerated* from SageAndLatexmk.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('SageAndLatexmk', version='2015/08/26 v3.0-92d9f7a', version_check=True)
try:
 _st_.current_tex_line = _sage_const_65 
 _st_.inline(_sage_const_0 , latex(_sage_const_32 **_sage_const_31 ))
except:
 _st_.goboom(_sage_const_65 )
try:
 _st_.current_tex_line = _sage_const_70 
 _st_.plot(_sage_const_0 , format='notprovided', _p_=plot(x * sin( _sage_const_30  * x), -_sage_const_1 , _sage_const_1 ))
except:
 _st_.goboom(_sage_const_70 )
try:
 _st_.current_tex_line = _sage_const_75 
 _st_.inline(_sage_const_1 , latex(integrate( (x**_sage_const_2  + x + _sage_const_1 ) / ((x - _sage_const_1 )**_sage_const_3  * (x**_sage_const_2  + x + _sage_const_2 )) )))
except:
 _st_.goboom(_sage_const_75 )
try:
 _st_.current_tex_line = _sage_const_80 
 _st_.inline(_sage_const_2 , latex(matrix([[_sage_const_1 , _sage_const_2 , _sage_const_3 ], [_sage_const_4 , _sage_const_5 , _sage_const_6 ], [_sage_const_7 , _sage_const_8 , _sage_const_9 ]])**_sage_const_3 ))
except:
 _st_.goboom(_sage_const_80 )
try:
 _st_.current_tex_line = _sage_const_82 
 _st_.inline(_sage_const_3 , latex(Matrix([[_sage_const_1 , _sage_const_2 ], [_sage_const_3 , _sage_const_4 ]])))
except:
 _st_.goboom(_sage_const_82 )
try:
 _st_.current_tex_line = _sage_const_82 
 _st_.inline(_sage_const_4 , latex(Matrix([[_sage_const_5 , _sage_const_6 ], [_sage_const_6 , _sage_const_8 ]])))
except:
 _st_.goboom(_sage_const_82 )
try:
 _st_.current_tex_line = _sage_const_82 
 _st_.inline(_sage_const_5 , latex(Matrix([[_sage_const_1 , _sage_const_2 ], [_sage_const_3 , _sage_const_4 ]]) * Matrix([[_sage_const_5 , _sage_const_6 ], [_sage_const_6 , _sage_const_8 ]])))
except:
 _st_.goboom(_sage_const_82 )
try:
 _st_.current_tex_line = _sage_const_86 
 _st_.plot(_sage_const_1 , format='notprovided', _p_=plot(x * ln(x), _sage_const_0 , _sage_const_2 ))
except:
 _st_.goboom(_sage_const_86 )
try:
 _st_.current_tex_line = _sage_const_90 
 _st_.inline(_sage_const_6 , latex(pi * e))
except:
 _st_.goboom(_sage_const_90 )
try:
 _st_.current_tex_line = _sage_const_90 
 _st_.inline(_sage_const_7 , latex(N(pi * e)))
except:
 _st_.goboom(_sage_const_90 )
_st_.endofdoc()

