## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file SageTest.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_29 = Integer(29); _sage_const_23 = Integer(23); _sage_const_25 = Integer(25); _sage_const_40 = Integer(40); _sage_const_44 = Integer(44); _sage_const_48 = Integer(48); _sage_const_38 = Integer(38); _sage_const_31 = Integer(31); _sage_const_30 = Integer(30); _sage_const_33 = Integer(33); _sage_const_32 = Integer(32); _sage_const_1324 = Integer(1324)## This file (SageTest.sagetex.sage) was *autogenerated* from SageTest.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('SageTest', version='2015/08/26 v3.0-92d9f7a', version_check=True)
try:
 _st_.current_tex_line = _sage_const_23 
 _st_.inline(_sage_const_0 , latex(_sage_const_32 **_sage_const_31 ))
except:
 _st_.goboom(_sage_const_23 )
try:
 _st_.current_tex_line = _sage_const_25 
 _st_.inline(_sage_const_1 , latex(_sage_const_1324 **_sage_const_9 ))
except:
 _st_.goboom(_sage_const_25 )
try:
 _st_.current_tex_line = _sage_const_29 
 _st_.plot(_sage_const_0 , format='notprovided', _p_=plot(x * sin( _sage_const_30  * x), -_sage_const_1 , _sage_const_1 ))
except:
 _st_.goboom(_sage_const_29 )
try:
 _st_.current_tex_line = _sage_const_33 
 _st_.inline(_sage_const_2 , latex(integrate( (x**_sage_const_2  + x + _sage_const_1 ) / ((x - _sage_const_1 )**_sage_const_3  * (x**_sage_const_2  + x + _sage_const_2 )), x )))
except:
 _st_.goboom(_sage_const_33 )
try:
 _st_.current_tex_line = _sage_const_38 
 _st_.inline(_sage_const_3 , latex(matrix([[_sage_const_1 , _sage_const_2 , _sage_const_3 ], [_sage_const_4 , _sage_const_5 , _sage_const_6 ], [_sage_const_7 , _sage_const_8 , _sage_const_9 ]])**_sage_const_3 ))
except:
 _st_.goboom(_sage_const_38 )
try:
 _st_.current_tex_line = _sage_const_40 
 _st_.inline(_sage_const_4 , latex(Matrix([[_sage_const_1 , _sage_const_2 ], [_sage_const_3 , _sage_const_4 ]])))
except:
 _st_.goboom(_sage_const_40 )
try:
 _st_.current_tex_line = _sage_const_40 
 _st_.inline(_sage_const_5 , latex(Matrix([[_sage_const_5 , _sage_const_6 ], [_sage_const_6 , _sage_const_8 ]])))
except:
 _st_.goboom(_sage_const_40 )
try:
 _st_.current_tex_line = _sage_const_40 
 _st_.inline(_sage_const_6 , latex(Matrix([[_sage_const_1 , _sage_const_2 ], [_sage_const_3 , _sage_const_4 ]]) * Matrix([[_sage_const_5 , _sage_const_6 ], [_sage_const_6 , _sage_const_8 ]])))
except:
 _st_.goboom(_sage_const_40 )
try:
 _st_.current_tex_line = _sage_const_44 
 _st_.plot(_sage_const_1 , format='notprovided', _p_=plot(x * ln(x), _sage_const_0 , _sage_const_2 ))
except:
 _st_.goboom(_sage_const_44 )
try:
 _st_.current_tex_line = _sage_const_48 
 _st_.inline(_sage_const_7 , latex(pi * e))
except:
 _st_.goboom(_sage_const_48 )
try:
 _st_.current_tex_line = _sage_const_48 
 _st_.inline(_sage_const_8 , latex(N(pi * e)))
except:
 _st_.goboom(_sage_const_48 )
_st_.endofdoc()

