# This file was *autogenerated* from the file SageTest.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(Integer(3)); _sage_const_2 = Integer(Integer(2)); _sage_const_1 = Integer(Integer(1)); _sage_const_0 = Integer(Integer(0)); _sage_const_7 = Integer(Integer(7)); _sage_const_6 = Integer(Integer(6)); _sage_const_5 = Integer(Integer(5)); _sage_const_4 = Integer(Integer(4)); _sage_const_9 = Integer(Integer(9)); _sage_const_8 = Integer(Integer(8)); _sage_const_42 = Integer(Integer(42)); _sage_const_38 = Integer(Integer(38)); _sage_const_46 = Integer(Integer(46)); _sage_const_30 = Integer(Integer(30)); _sage_const_31 = Integer(Integer(31)); _sage_const_23 = Integer(Integer(23)); _sage_const_32 = Integer(Integer(32)); _sage_const_27 = Integer(Integer(27)); _sage_const_36 = Integer(Integer(36))
import sys
sys.path.insert(_sage_const_0 , '/Applications/sage')
import sagetex
sagetex.openout('SageTest')
try:
 sagetex.inline(_sage_const_0 , _sage_const_32 **_sage_const_31 )
except:
 sagetex.goboom(_sage_const_23 )
try:
 sagetex.initplot('SageTest')
 sagetex.plot(_sage_const_0 , plot(x * sin( _sage_const_30  * x), -_sage_const_1 , _sage_const_1 ), format='notprovided', epsmagick=False)
except:
 sagetex.goboom(_sage_const_27 )
try:
 sagetex.inline(_sage_const_1 , integrate( (x**_sage_const_2  + x + _sage_const_1 ) / ((x - _sage_const_1 )**_sage_const_3  * (x**_sage_const_2  + x + _sage_const_2 )) ))
except:
 sagetex.goboom(_sage_const_31 )
try:
 sagetex.inline(_sage_const_2 , matrix([[_sage_const_1 , _sage_const_2 , _sage_const_3 ], [_sage_const_4 , _sage_const_5 , _sage_const_6 ], [_sage_const_7 , _sage_const_8 , _sage_const_9 ]])**_sage_const_3 )
except:
 sagetex.goboom(_sage_const_36 )
try:
 sagetex.inline(_sage_const_3 , Matrix([[_sage_const_1 , _sage_const_2 ], [_sage_const_3 , _sage_const_4 ]]))
except:
 sagetex.goboom(_sage_const_38 )
try:
 sagetex.inline(_sage_const_4 , Matrix([[_sage_const_5 , _sage_const_6 ], [_sage_const_6 , _sage_const_8 ]]))
except:
 sagetex.goboom(_sage_const_38 )
try:
 sagetex.inline(_sage_const_5 , Matrix([[_sage_const_1 , _sage_const_2 ], [_sage_const_3 , _sage_const_4 ]]) * Matrix([[_sage_const_5 , _sage_const_6 ], [_sage_const_6 , _sage_const_8 ]]))
except:
 sagetex.goboom(_sage_const_38 )
try:
 sagetex.initplot('SageTest')
 sagetex.plot(_sage_const_1 , plot(x * ln(x), _sage_const_0 , _sage_const_2 ), format='notprovided', epsmagick=False)
except:
 sagetex.goboom(_sage_const_42 )
try:
 sagetex.inline(_sage_const_6 , pi * e)
except:
 sagetex.goboom(_sage_const_46 )
try:
 sagetex.inline(_sage_const_7 , N(pi * e))
except:
 sagetex.goboom(_sage_const_46 )
sagetex.endofdoc()
