# This file was *autogenerated* from the file SageTest.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_42 = Integer(42); _sage_const_38 = Integer(38); _sage_const_46 = Integer(46); _sage_const_30 = Integer(30); _sage_const_31 = Integer(31); _sage_const_23 = Integer(23); _sage_const_32 = Integer(32); _sage_const_27 = Integer(27); _sage_const_36 = Integer(36)## This file (SageTest.sage) was *autogenerated* from the file SageTest.tex.
import sagetex
_st_ = sagetex.SageTeXProcessor('SageTest')
try:
 _st_.inline(_sage_const_0 , latex(_sage_const_32 **_sage_const_31 ))
except:
 _st_.goboom(_sage_const_23 )
try:
 _st_.plot(_sage_const_0 , format='notprovided', _p_=plot(x * sin( _sage_const_30  * x), -_sage_const_1 , _sage_const_1 ))
except:
 _st_.goboom(_sage_const_27 )
try:
 _st_.inline(_sage_const_1 , latex(integrate( (x**_sage_const_2  + x + _sage_const_1 ) / ((x - _sage_const_1 )**_sage_const_3  * (x**_sage_const_2  + x + _sage_const_2 )) )))
except:
 _st_.goboom(_sage_const_31 )
try:
 _st_.inline(_sage_const_2 , latex(matrix([[_sage_const_1 , _sage_const_2 , _sage_const_3 ], [_sage_const_4 , _sage_const_5 , _sage_const_6 ], [_sage_const_7 , _sage_const_8 , _sage_const_9 ]])**_sage_const_3 ))
except:
 _st_.goboom(_sage_const_36 )
try:
 _st_.inline(_sage_const_3 , latex(Matrix([[_sage_const_1 , _sage_const_2 ], [_sage_const_3 , _sage_const_4 ]])))
except:
 _st_.goboom(_sage_const_38 )
try:
 _st_.inline(_sage_const_4 , latex(Matrix([[_sage_const_5 , _sage_const_6 ], [_sage_const_6 , _sage_const_8 ]])))
except:
 _st_.goboom(_sage_const_38 )
try:
 _st_.inline(_sage_const_5 , latex(Matrix([[_sage_const_1 , _sage_const_2 ], [_sage_const_3 , _sage_const_4 ]]) * Matrix([[_sage_const_5 , _sage_const_6 ], [_sage_const_6 , _sage_const_8 ]])))
except:
 _st_.goboom(_sage_const_38 )
try:
 _st_.plot(_sage_const_1 , format='notprovided', _p_=plot(x * ln(x), _sage_const_0 , _sage_const_2 ))
except:
 _st_.goboom(_sage_const_42 )
try:
 _st_.inline(_sage_const_6 , latex(pi * e))
except:
 _st_.goboom(_sage_const_46 )
try:
 _st_.inline(_sage_const_7 , latex(N(pi * e)))
except:
 _st_.goboom(_sage_const_46 )
_st_.endofdoc()
